(function(g){var window=this;var SAa=function(a,b){return g.Vb(a,b)},c6=function(a){g.Jm(a,"zx",g.xb());
return a},d6=function(a,b,c){g.za(c)||(c=[String(c)]);
g.Mm(a.g,b,c)},TAa=function(a,b){var c=[];
g.rk(b,function(a){try{var b=g.$C.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.ZC(b)&&c.push(a):c.push(a)},a);
return c},UAa=function(a,b){var c=TAa(a,b);
(0,g.B)(c,function(a){g.$C.prototype.remove.call(this,a)},a)},VAa=function(a,b,c,d){var e=new g.Am(null,void 0);
a&&g.Bm(e,a);b&&g.Cm(e,b);c&&g.Dm(e,c);d&&g.Em(e,d);return e},WAa=function(a){g.UF[a]&&(a=g.UF[a],(0,g.B)(a,function(a){g.SF[a]&&delete g.SF[a]}),a.length=0)},XAa=function(a){var b=g.RF();
if(b)if(b.clear(a),a)WAa(a);else for(var c in g.UF)WAa(c)},e6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.um;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",YAa(this,a.capabilities||""),ZAa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},YAa=function(a,b){a.capabilities.clear();
(0,g.Jd)(b.split(","),g.Fa(SAa,$Aa)).forEach(function(b){a.capabilities.add(b)})},ZAa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},f6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},g6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},aBa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},bBa=function(a){return new f6(a)},cBa=function(a){return g.za(a)?(0,g.I)(a,bBa):[]},h6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},i6=function(a){return g.za(a)?"["+(0,g.I)(a,h6).join(",")+"]":"null"},j6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},dBa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},k6=function(a,b){return g.Ma(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},l6=function(a,b){return g.Ma(a,function(a){return g6(a,b)})},eBa=function(){var a=(0,g.NG)();
a&&UAa(a,a.g.Qd(!0))},m6=function(){var a=g.QG("yt-remote-connected-devices")||[];
g.ib(a);return a},fBa=function(a){if(g.Qa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},gBa=function(a){g.PG("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.QG("yt-remote-device-id");a||(a=j6(),g.PG("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.D(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.D(a,b);g.SG()&&g.kb(a,b);a=fBa(a);if(g.Qa(a))try{g.AG("remote_sid")}catch(c){}else try{g.zG("remote_sid",a.join(","),-1)}catch(c){}},hBa=function(){return g.QG("yt-remote-session-browser-channel")},iBa=function(){return g.QG("yt-remote-local-screens")||[]},jBa=function(){g.PG("yt-remote-lounge-token-expiration",!0,86400)},kBa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(iBa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.jm)(c,function(a){return!g.D(b,a)})&&jBa();
g.PG("yt-remote-local-screens",a,31536E3)},lBa=function(a,b){g.PG("yt-remote-session-browser-channel",a);
g.PG("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.D(c,d)||c.push(d);gBa(c);p6()},q6=function(a){a||(g.RG("yt-remote-session-screen-id"),g.RG("yt-remote-session-video-id"));
p6();a=m6();g.Ua(a,o6());gBa(a)},mBa=function(){if(!r6){var a=g.kD();
a&&(r6=new g.UC(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},nBa=function(){var a=window.document.createElement("a");
g.Yc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Bb(a)},oBa=function(a,b){var c=g.Cd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Zc(c,g.be("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},pBa=function(){var a=nBa(),b=window.document.getElementById(a),c=b&&g.fF(b,"loaded");
c||b&&!c||(b=oBa(a,function(){g.fF(b,"loaded")||(g.eF(b,"loaded","true"),g.YF(a),g.TD(g.Fa(XAa,a),0))}))},s6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},qBa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},t6=function(a){a.length?rBa(a.shift(),function(){t6(a)}):u6()},sBa=function(a){return"chrome-extension://"+a+v6},rBa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},w6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},u6=function(){var a=qBa();
a&&a(!1,"No cast extension found")},x6=function(){if(tBa){var a=2,b=qBa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;rBa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},uBa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(x6(),a({command:"cast.sender.init"}))},vBa=function(){x6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);t6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+v6,"//www.gstatic.com/eureka/clank"+v6])},y6=function(a,b,c){g.L.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.ed=b;this.B=(0,g.z)(this.uI,this);this.g=!1;this.l=0;this.o=this.ya=null;this.A=[]},z6=function(){},A6=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.D=d||1;this.B=45E3;this.A=new g.Qm(this);this.l=new g.sg;this.l.setInterval(250)},xBa=function(a,b,c){a.xj=1;
a.hh=c6(b.clone());a.Ji=c;a.C=!0;wBa(a,null)},B6=function(a,b,c,d,e){a.xj=1;
a.hh=c6(b.clone());a.Ji=null;a.C=c;e&&(a.LC=!1);wBa(a,d)},wBa=function(a,b){a.dk=(0,g.G)();
C6(a);a.Ah=a.hh.clone();d6(a.Ah,"t",a.D);a.im=0;a.Sc=a.g.Dq(a.g.Yl()?b:null);0<a.ir&&(a.So=new g.Tk((0,g.z)(a.bE,a,a.Sc),a.ir));a.A.T(a.Sc,"readystatechange",a.xT);var c=a.ki?g.bc(a.ki):{};a.Ji?(a.Cp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Sc.send(a.Ah,a.Cp,a.Ji,c)):(a.Cp="GET",a.LC&&!g.yd&&(c.Connection="close"),a.Sc.send(a.Ah,a.Cp,null,c));a.g.rf(1)},ABa=function(a,b,c){for(var d=!0;!a.Uh&&a.im<c.length;){var e=yBa(a,c);
if(e==D6){4==b&&(a.ih=4,E6(15),d=!1);break}else if(e==zBa){a.ih=4;E6(16);d=!1;break}else F6(a,e)}4==b&&0==c.length&&(a.ih=1,E6(17),d=!1);a.xf=a.xf&&d;d||(G6(a),H6(a))},yBa=function(a,b){var c=a.im,d=b.indexOf("\n",c);
if(-1==d)return D6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return zBa;d+=1;if(d+c>b.length)return D6;var e=b.substr(d,c);a.im=d+c;return e},CBa=function(a,b){a.dk=(0,g.G)();
C6(a);var c=b?window.location.hostname:"";a.Ah=a.hh.clone();g.Jm(a.Ah,"DOMAIN",c);g.Jm(a.Ah,"t",a.D);try{a.yf=new window.ActiveXObject("htmlfile")}catch(n){G6(a);a.ih=7;E6(22);H6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in I6)k=I6[l];else if(l in BBa)k=I6[l]=BBa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=I6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.$c(g.vc("b/12014412"),d);a.yf.open();a.yf.write(g.Rc(c));a.yf.close();a.yf.parentWindow.m=(0,g.z)(a.FS,a);a.yf.parentWindow.d=(0,g.z)(a.YB,a,!0);a.yf.parentWindow.rpcClose=(0,g.z)(a.YB,a,!1);c=a.yf.createElement("DIV");a.yf.parentWindow.document.body.appendChild(c);d=g.Ic(a.Ah.toString());d=g.rb(g.Fc(d));d=g.$c(g.vc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Rc(d);
a.g.rf(1)},C6=function(a){a.Wu=(0,g.G)()+a.B;
DBa(a,a.B)},DBa=function(a,b){if(null!=a.xk)throw Error("WatchDog timer not null");
a.xk=J6((0,g.z)(a.WS,a),b)},K6=function(a){a.xk&&(g.w.clearTimeout(a.xk),a.xk=null)},H6=function(a){a.g.by()||a.Uh||a.g.Go(a)},G6=function(a){K6(a);
g.af(a.So);a.So=null;a.l.stop();g.Wm(a.A);if(a.Sc){var b=a.Sc;a.Sc=null;b.abort();b.dispose()}a.yf&&(a.yf=null)},F6=function(a,b){try{a.g.RB(a,b),a.g.rf(4)}catch(c){}},FBa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;EBa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){FBa(a,b,c,d,f)},f)})}},EBa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{L6(d),c(!0)}catch(e){}};
d.onerror=function(){try{L6(d),c(!1)}catch(e){}};
d.onabort=function(){try{L6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{L6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},L6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},GBa=function(a){this.g=a;
this.l=new z6},HBa=function(a){var b=M6(a.g,a.Ck,"/mail/images/cleardot.gif");
c6(b);FBa(b.toString(),5E3,(0,g.z)(a.GH,a),3,2E3);a.rf(1)},O6=function(a){var b=a.g.H;
if(null!=b)E6(5),b?(E6(11),N6(a.g,a,!1)):(E6(12),N6(a.g,a,!0));else if(a.ue=new A6(a,void 0,void 0,void 0),a.ue.ki=a.dr,b=a.g,b=M6(b,b.Yl()?a.bl:null,a.gr),E6(5),!g.wd||g.rc(10))d6(b,"TYPE","xmlhttp"),B6(a.ue,b,!1,a.bl,!1);else{d6(b,"TYPE","html");var c=a.ue;a=!!a.bl;c.xj=3;c.hh=c6(b.clone());CBa(c,a)}},P6=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new z6;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},IBa=function(a,b){this.g=a;
this.map=b;this.context=null},JBa=function(a){g.cf.call(this,"statevent",a)},KBa=function(a,b){g.cf.call(this,"timingevent",a);
this.size=b},LBa=function(a){g.cf.call(this,"serverreachability",a)},OBa=function(a){MBa(a);
if(3==a.g){var b=a.Jl++,c=a.Cn.clone();g.Jm(c,"SID",a.o);g.Jm(c,"RID",b);g.Jm(c,"TYPE","terminate");Q6(a,c);b=new A6(a,a.o,b,void 0);b.xj=2;b.hh=c6(c.clone());(new window.Image).src=b.hh;b.dk=(0,g.G)();C6(b)}NBa(a)},PBa=function(a){a.bI(1,0);
a.Cn=M6(a,null,a.ar);R6(a)},MBa=function(a){a.Wg&&(a.Wg.abort(),a.Wg=null);
a.wc&&(a.wc.cancel(),a.wc=null);a.pg&&(g.w.clearTimeout(a.pg),a.pg=null);S6(a);a.Vd&&(a.Vd.cancel(),a.Vd=null);a.Yg&&(g.w.clearTimeout(a.Yg),a.Yg=null)},QBa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new IBa(a.wO++,b));2!=a.g&&3!=a.g||R6(a)},R6=function(a){a.Vd||a.Yg||(a.Yg=J6((0,g.z)(a.WB,a),0),a.pj=0)},SBa=function(a,b){if(1==a.g){if(!b){a.Jl=Math.floor(1E5*Math.random());
var c=a.Jl++,d=new A6(a,"",c,void 0);d.ki=null;var e=T6(a),f=a.Cn.clone();g.Jm(f,"RID",c);g.Jm(f,"CVER","1");Q6(a,f);xBa(d,f,e);a.Vd=d;a.g=2}}else 3==a.g&&(b?RBa(a,b):0==a.l.length||a.Vd||RBa(a))},RBa=function(a,b){if(b)if(6<a.Wh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.Jl-1;var d=T6(a)}else c=b.F,d=b.Ji;else c=a.Jl++,d=T6(a);var e=a.Cn.clone();g.Jm(e,"SID",a.o);g.Jm(e,"RID",c);g.Jm(e,"AID",a.Mj);Q6(a,e);c=new A6(a,a.o,c,a.pj+1);c.ki=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Vd=c;xBa(c,e,d)},Q6=function(a,b){if(a.qd){var c=a.qd.Jx();
c&&g.Lb(c,function(a,c){g.Jm(b,c,a)})}},T6=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Wh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Wh?e:f-d;try{g.Lb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},TBa=function(a){a.wc||a.pg||(a.D=1,a.pg=J6((0,g.z)(a.VB,a),0),a.dj=0)},U6=function(a){if(a.wc||a.pg||3<=a.dj)return!1;
a.D++;a.pg=J6((0,g.z)(a.VB,a),UBa(a,a.dj));a.dj++;return!0},N6=function(a,b,c){a.Bp=c;
a.If=b.xg;a.C||PBa(a)},S6=function(a){null!=a.Yh&&(g.w.clearTimeout(a.Yh),a.Yh=null)},UBa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},V6=function(a,b){if(2==b||9==b){var c=null;
a.qd&&(c=null);var d=(0,g.z)(a.sU,a);c||(c=new g.Am("//www.google.com/images/cleardot.gif"),c6(c));EBa(c.toString(),1E4,d)}else E6(2);VBa(a,b)},VBa=function(a,b){a.g=0;
a.qd&&a.qd.Aw(b);NBa(a);MBa(a)},NBa=function(a){a.g=0;
a.If=-1;if(a.qd)if(0==a.A.length&&0==a.l.length)a.qd.qq();else{g.Xa(a.A);var b=g.Xa(a.l);a.A.length=0;a.l.length=0;a.qd.qq(b)}},M6=function(a,b,c){var d=g.Km(c);
if(""!=d.l)b&&g.Cm(d,b+"."+d.l),g.Dm(d,d.B);else{var e=window.location;d=VAa(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Nk&&g.Lb(a.Nk,function(a,b){g.Jm(d,b,a)});
g.Jm(d,"VER",a.Wh);Q6(a,d);return d},J6=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},E6=function(a){W6.dispatchEvent(new JBa(W6,a))},WBa=function(){},XBa=function(a,b){this.action=a;
this.params=b||{}},X6=function(a,b){g.L.call(this);
this.g=new g.Yt(this.wS,0,this);g.M(this,this.g);this.ed=5E3;this.l=0;if(g.Ba(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},Y6=function(a,b,c){this.K=a;
this.C=b;this.o=new g.TC;this.l=new X6(this.XU,this);this.g=this.Ya=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.M=c||!1},YBa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Bp,sessionId:a.g.o,arrayId:a.g.Mj}},ZBa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&SBa(a.g),OBa(a.g));a.F=0},Z6=function(a){return!!a.g&&3==a.g.g},$Ba=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},$6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Jg(a)||"";b&&(this.port=":"+b);this.domain=g.Ig(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ab(a,"10.0")&&(this.l=!1))},a7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Sg(c+b,{})},b7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,Ib:g.Fa(a.A,d,!0),onError:g.Fa(a.o,e),wd:g.Fa(a.B,e)};c&&(a.Mb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.qE(b,a)},dCa=function(){var a=aCa;
bCa();c7.push(a);cCa(c7)},d7=function(a,b){bCa();
var c=c7,d=eCa(a,String(b));g.Qa(c)?fCa(d):(cCa(c),(0,g.B)(c,function(a){a(d)}))},bCa=function(){c7||(c7=g.x("yt.mdx.remote.debug.handlers_")||[],g.wa("yt.mdx.remote.debug.handlers_",c7,void 0))},fCa=function(a){var b=(e7+1)%50;
e7=b;f7[b]=a;g7||(g7=49==b)},cCa=function(a){var b=f7;
if(b[0]){var c=e7,d=g7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(a){a(e)})}while(d!=c);
f7=Array(50);e7=-1;g7=!1}},eCa=function(a,b){var c=((0,g.G)()-gCa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},h7=function(a){g.KF.call(this);
this.D=a;this.g=[]},hCa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},iCa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Jd)(a.g,function(a){return!!k6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=hCa(a,b[d])||c;return c},jCa=function(a,b){var c=a.g.length;
a.g=(0,g.Jd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},i7=function(a,b,c,d){g.KF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.ya=window.NaN},k7=function(a){h7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;j7(this);this.info("Initializing with "+i6(this.g))},kCa=function(a){if(a.g.length){var b=(0,g.I)(a.g,function(a){return a.id}),c=a7(a.o,"/pairing/get_lounge_token_batch");
b7(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.HI,a),(0,g.z)(a.GI,a))}},j7=function(a){var b=cBa(iBa());
b=(0,g.Jd)(b,function(a){return!a.uuid});
return iCa(a,b)},l7=function(a,b){kBa((0,g.I)(a.g,aBa));
b&&jBa()},n7=function(a,b){g.KF.call(this);
this.C=b;var c=g.QG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.D(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;m7("Initialized with "+g.zg(this.g))},lCa=function(a,b,c){var d=a7(a.B,"/pairing/get_screen_availability");
b7(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},o7=function(a,b){a:if(g.Pb(b)!=g.Pb(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(m7("Updated online screens: "+g.zg(a.g)),a.g=b,a.R("screenChange"));mCa(a)},p7=function(a){(0,window.isNaN)(a.o)||g.ZD(a.o);
a.o=g.TD((0,g.z)(a.fu,a),0<a.A&&a.A<(0,g.G)()?2E4:1E4)},m7=function(a){d7("OnlineScreenService",a)},nCa=function(a){var b={};
(0,g.B)(a.C(),function(a){a.token?b[a.token]=a.id:this.gc("Requesting availability of screen w/o lounge token.")});
return b},mCa=function(a){a=g.Sb(g.Mb(a.g,function(a){return a}));
g.ib(a);a.length?g.PG("yt-remote-online-screen-ids",a.join(","),60):g.RG("yt-remote-online-screen-ids")},q7=function(a){h7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};oCa(this)},qCa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ne();if(k=(c?l6(k,c):null)||l6(k,b)){k.uuid=b;var l=r7(a,k);lCa(a.l,l,function(a){e(a?l:null)})}else c?pCa(a,c,(0,g.z)(function(a){var f=r7(this,new f6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));lCa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},rCa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},pCa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Mb:{screen_ids:b},method:"POST",context:a,Ib:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.qE(a7(a.C,"/pairing/get_lounge_token_batch"),e)},sCa=function(a){a.g=a.o.ne();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+i6(a.g))},oCa=function(a){s7(a);
a.o=new k7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.YI,a));sCa(a);a.A=cBa(g.QG("yt-remote-automatic-screen-cache")||[]);s7(a);a.info("Initializing automatic screens: "+i6(a.A));a.l=new n7(a.C,(0,g.z)(a.ne,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.R("onlineScreenChange")},a))},r7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=l6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.PG("yt-remote-automatic-screen-cache",(0,g.I)(a.A,aBa)));s7(a);a.B[b.uuid]=b.id;g.PG("yt-remote-device-id-map",a.B,31536E3);return b},s7=function(a){a.B=g.QG("yt-remote-device-id-map")||{}},t7=function(a,b,c){g.KF.call(this);
this.M=c;this.H=a;this.l=b;this.o=null},u7=function(a,b){d7(a.M,b)},v7=function(a,b){t7.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.dV,this);this.B=(0,g.z)(this.hT,this);this.A=g.TD((0,g.z)(function(){tCa(this,null)},this),12E4)},uCa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.zg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){u7(this,"Failed to send message: getMdxSessionStatus.")},a)):u7(a,"Sending yt message without session: "+g.zg(b))},tCa=function(a,b){g.ZD(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.Ho,a),d=(0,g.z)(a.se,a);a.Ux(b,c,d,5)}}else a.se(Error("Waiting for session status timed out."))},w7=function(a,b,c){t7.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.N=c;this.B=null;this.D=g.y;this.C=window.NaN;this.K=(0,g.z)(this.gV,this);this.g=g.y},vCa=function(a){a.g=a.H.iE(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.Ho(a)},a),(0,g.z)(function(a){this.g=g.y;
this.se(a)},a))},wCa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}mBa()&&(b.env_useStageMdx=1);return g.Qg(b)},x7=function(a,b){t7.call(this,a,b,"ManualSession");
this.g=g.TD((0,g.z)(this.Nj,this,null),150)},y7=function(a,b,c,d){g.KF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.KR,this)},xCa=function(a,b){return b?g.Ma(a.o,function(a){return g6(b,a.label)},a):null},z7=function(a){d7("Controller",a)},aCa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},A7=function(a){return a.B||!!a.o.length||!!a.g},B7=function(a,b,c){b!=a.g&&(g.af(a.g),(a.g=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.l):a.R("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.TB,a,b)),b.o?a.R("yt-remote-cast2-session-change",b.o):c&&a.g.Nj(null)):a.R("yt-remote-cast2-session-change",null))},yCa=function(a){var b=a.l.hE(),c=a.g&&a.g.l;
a=(0,g.I)(b,function(a){c&&g6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=xCa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},ECa=function(a,b,c,d,e,f,k){zCa()?ACa(b,e,f,k)&&(D7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?BCa(a,c):(window.__onGCastApiAvailable=function(b,d){b?BCa(a,c):(E7("Failed to load cast API: "+d),F7(!1),D7(!1),g.RG("yt-remote-cast-available"),g.RG("yt-remote-cast-receiver"),CCa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):pBa():w6("CriOS")?uBa():w6("Android")&&w6("Chrome/")&&window.navigator.presentation?vBa():window.chrome&&window.navigator.presentation&&!w6("Edge")?(x6(),t6(DCa.map(sBa))):u6())):C7("Cannot initialize because not running Chrome")},CCa=function(){C7("dispose");
var a=G7();a&&a.dispose();g.wa("yt.mdx.remote.cloudview.instance_",null,void 0);FCa(!1);g.WF(H7);H7.length=0},I7=function(){return!!g.QG("yt-remote-cast-installed")},GCa=function(){var a=g.QG("yt-remote-cast-receiver");
return a?a.friendlyName:null},HCa=function(){C7("clearCurrentReceiver");
g.RG("yt-remote-cast-receiver")},ICa=function(){return I7()?G7()?G7().getCastSession():(E7("getCastSelector: Cast is not initialized."),null):(E7("getCastSelector: Cast API is not installed!"),null)},K7=function(){I7()?G7()?J7()?(C7("Requesting cast selector."),G7().requestSession()):(C7("Wait for cast API to be ready to request the session."),H7.push(g.VF("yt-remote-cast2-api-ready",K7))):E7("requestCastSelector: Cast is not initialized."):E7("requestCastSelector: Cast API is not installed!")},L7=
function(a,b){J7()?G7().setConnectedScreenStatus(a,b):E7("setConnectedScreenStatus called before ready.")},zCa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.SJ||a},JCa=function(a,b){G7().init(a,b)},ACa=function(a,b,c,d){var e=!1;
G7()||(a=new y7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.PG("yt-remote-cast-available",a);g.ZF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){C7("onReceiverSelected: "+a.friendlyName);
g.PG("yt-remote-cast-receiver",a);g.ZF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){C7("onReceiverResumed: "+a.friendlyName);
g.PG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){C7("onSessionChange: "+h6(a));
a||g.RG("yt-remote-cast-receiver");g.ZF("yt-remote-cast2-session-change",a)}),g.wa("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
C7("cloudview.createSingleton_: "+e);return e},G7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},BCa=function(a,b){F7(!0);
D7(!1);JCa(a,function(a){a?(FCa(!0),g.YF("yt-remote-cast2-api-ready")):(E7("Failed to initialize cast API."),F7(!1),g.RG("yt-remote-cast-available"),g.RG("yt-remote-cast-receiver"),CCa());b(a)})},C7=function(a){d7("cloudview",a)},E7=function(a){d7("cloudview",a)},F7=function(a){C7("setCastInstalled_ "+a);
g.PG("yt-remote-cast-installed",a)},J7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},FCa=function(a){C7("setApiReady_ "+a);
g.wa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},D7=function(a){g.wa("yt.mdx.remote.cloudview.initializing_",a,void 0)},M7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Lf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},N7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Lf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.G)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},O7=function(a){return a.kb()?((0,g.G)()-a.D)/1E3:0},P7=function(a,b){a.F=b;
a.D=(0,g.G)()},Q7=function(a){switch(a.g){case 1:case 1081:return((0,g.G)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},R7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&N7(a)},S7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.l);b.hasPrevious=a.Lf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},U7=function(a,b){g.KF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.jC;this.o=this.l=null;this.H=(0,g.z)(this.gP,this);this.D=(0,g.z)(this.Ml,this);this.F=(0,g.z)(this.fP,this);this.I=(0,g.z)(this.tP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.cv,this),KCa(this))):c=3;0!=c&&(b?this.cv(c):g.TD((0,g.z)(function(){this.cv(c)},this),0));
var d=ICa();d&&T7(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},V7=function(a){return new M7(a.A.getPlayerContextData())},KCa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Fa(this.GR,a),this))},a)},LCa=function(a){(0,g.B)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},W7=function(a,b){50>a.B.Fc()&&g.lC(a.B,b)},Y7=function(a,b,c){var d=V7(a);
P7(d,c);-1E3!=d.g&&(d.g=b);X7(a,d)},Z7=function(a,b,c){a.A.sendMessage(b,c)},X7=function(a,b){LCa(a);
a.A.setPlayerContextData(S7(b));KCa(a)},T7=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.Ml(null));
a.o=b;a.o&&(d7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.Ml(a.o.media[0]))},MCa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=V7(a);b.contentId!=d.videoId&&d7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;P7(d,a.l.getEstimatedTime());X7(a,d)}else d7("CP","No cast media video. Ignoring state update.")},$7=function(a,b,c){return(0,g.z)(function(a){this.gc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.gc("Retrying "+b+" using MDx browser channel."),Z7(this,b,c))},a)},a8=function(a,b,c){g.KF.call(this);
this.B=window.NaN;this.N=!1;this.I=this.H=this.K=this.M=window.NaN;this.P=[];this.A=this.D=this.o=this.Za=this.g=null;this.oa=a;this.P.push(g.uF(window,"beforeunload",(0,g.z)(this.yI,this)));this.l=[];this.Za=new M7;this.X=b.id;this.g=NCa(this,c);this.g.subscribe("handlerOpened",this.kP,this);this.g.subscribe("handlerClosed",this.hP,this);this.g.subscribe("handlerError",this.iP,this);this.g.subscribe("handlerMessage",this.jP,this);$Ba(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Za.videoId;g.SG()&&g.PG("yt-remote-session-video-id",a)},this)},b8=function(a){d7("conn",a)},NCa=function(a,b){return new Y6(a7(a.oa,"/bc"),b)},c8=function(a,b){a.R("proxyStateChange",b)},OCa=function(a){a.B=g.TD((0,g.z)(function(){b8("Connecting timeout");
this.C(1)},a),2E4)},d8=function(a){g.ZD(a.B);
a.B=window.NaN},e8=function(a){g.ZD(a.M);
a.M=window.NaN},PCa=function(a){f8(a);
a.K=g.TD((0,g.z)(function(){g8(this,"getNowPlaying")},a),2E4)},f8=function(a){g.ZD(a.K);
a.K=window.NaN},RCa=function(a,b){b&&(d8(a),e8(a));
b==(Z6(a.g)&&(0,window.isNaN)(a.B))?b&&(c8(a,1),g8(a,"getSubtitlesTrack")):b?(a.W()&&a.Za.reset(),c8(a,1),g8(a,"getNowPlaying"),QCa(a)):a.C(1)},SCa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Za.videoId&&(g.Yb(b.params)?a.Za.l=null:a.Za.l=b.params,a.R("remotePlayerChange"))},TCa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Za.listId=b.params.listId||a.Za.listId;R7(a.Za,c,d);a.R("remoteQueueChange")},VCa=function(a,b){b.params=b.params||{};
TCa(a,b);UCa(a,b);a.R("autoplayDismissed")},UCa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
P7(a.Za,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Za.g&&(c=-1E3);a.Za.g=c;c=Number(b.params.loadedTime);a.Za.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Za.H=(0,window.isNaN)(c)?0:c;c=a.Za;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Za;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Za.g?PCa(a):f8(a);
a.R("remotePlayerChange")},WCa=function(a,b){if(-1E3!=a.Za.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Za.g=c;c=(0,window.parseInt)(b.params.currentTime,10);P7(a.Za,(0,window.isNaN)(c)?0:c);a.R("remotePlayerChange")}},XCa=function(a,b){var c="true"==b.params.muted;
a.Za.volume=(0,window.parseInt)(b.params.volume,10);a.Za.muted=c;a.R("remotePlayerChange")},YCa=function(a,b){a.D=b.params.videoId;
a.R("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},ZCa=function(a,b){var c="true"==b.params.hasNext;
a.Za.Lf="true"==b.params.hasPrevious;a.Za.hasNext=c;a.R("previousNextChange")},QCa=function(a){g.ZD(a.I);
a.I=g.TD((0,g.z)(a.C,a,1),864E5)},g8=function(a,b,c){c?b8("Sending: action="+b+", params="+g.zg(c)):b8("Sending: action="+b);
a.g.sendMessage(b,c)},h8=function(a){h7.call(this,"ScreenServiceProxy");
this.dd=a;this.l=[];this.l.push(this.dd.$_s("screenChange",(0,g.z)(this.bV,this)));this.l.push(this.dd.$_s("onlineScreenChange",(0,g.z)(this.gR,this)))},dDa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.ND("MDX_CONFIG")||b;eBa();p6();i8||(i8=new $6(b?b.loungeApiHost:void 0),mBa()&&(i8.g="/api/loungedev"));j8||(j8=g.x("yt.mdx.remote.deferredProxies_")||[],g.wa("yt.mdx.remote.deferredProxies_",j8,void 0));$Ca();var c=k8();if(!c){var d=new q7(i8);g.wa("yt.mdx.remote.screenService_",d,void 0);c=k8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);ECa(a,d,function(a){a?l8()&&L7(l8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.ZF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.wa("yt.mdx.remote.initialized_",!0,void 0),m8("Initializing: "+g.zg(b)),n8.push(g.VF("yt-remote-cast2-availability-change",function(){g.ZF("yt-remote-receiver-availability-change")})),n8.push(g.VF("yt-remote-cast2-receiver-selected",function(){o8(null);
g.ZF("yt-remote-auto-connect","cast-selector-receiver")})),n8.push(g.VF("yt-remote-cast2-receiver-resumed",function(){g.ZF("yt-remote-receiver-resumed","cast-selector-receiver")})),n8.push(g.VF("yt-remote-cast2-session-change",aDa)),n8.push(g.VF("yt-remote-connection-change",function(a){a?L7(l8(),"YouTube TV"):p8()||(L7(null,null),HCa())})),a=q8(),b.isAuto&&(a.id+="#dial"),g.LE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),m8(" -- with channel params: "+
g.zg(a)),bDa(a),c.start(),l8()||cDa())},fDa=function(){var a=eDa();
I7()&&g.QG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},eDa=function(){var a=k8().dd.$_gos();
var b=r8();b&&s8()&&(k6(a,b)||a.push(b));return dBa(a)},t8=function(){var a=gDa();
!a&&I7()&&GCa()&&(a={key:"cast-selector-receiver",name:GCa()});return a},gDa=function(){var a=eDa(),b=r8();
b||(b=p8());return g.Ma(a,function(a){return b&&g6(b,a.key)?!0:!1})},r8=function(){var a=l8();
if(!a)return null;var b=k8().ne();return l6(b,a)},aDa=function(a){m8("remote.onCastSessionChange_: "+h6(a));
if(a){var b=r8();b&&b.id==a.id?L7(b.id,"YouTube TV"):(b&&u8(),v8(a,1))}else s8()&&u8()},u8=function(){J7()?G7().stopSession():E7("stopSession called before API ready.");
var a=s8();a&&(a.disconnect(1),w8(null))},x8=function(){var a=s8();
return!!a&&3!=a.getProxyState()},m8=function(a){d7("remote",a)},k8=function(){if(!y8){var a=g.x("yt.mdx.remote.screenService_");
y8=a?new h8(a):null}return y8},l8=function(){return g.x("yt.mdx.remote.currentScreenId_")},hDa=function(a){g.wa("yt.mdx.remote.currentScreenId_",a,void 0)},iDa=function(){return g.x("yt.mdx.remote.connectData_")},o8=function(a){g.wa("yt.mdx.remote.connectData_",a,void 0)},s8=function(){return g.x("yt.mdx.remote.connection_")},w8=function(a){var b=s8();
o8(null);a||hDa("");g.wa("yt.mdx.remote.connection_",a,void 0);j8&&((0,g.B)(j8,function(b){b(a)}),j8.length=0);
b&&!a?g.ZF("yt-remote-connection-change",!1):!b&&a&&g.ZF("yt-remote-connection-change",!0)},p8=function(){var a=g.SG();
if(!a)return null;var b=k8().ne();return l6(b,a)},v8=function(a,b){r8()&&r8();
hDa(a.id);var c=new a8(i8,a,q8());c.connect(b,iDa());c.subscribe("beforeDisconnect",function(a){g.ZF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){s8()&&w8(null)});
w8(c)},cDa=function(){var a=p8();
a?(m8("Resume connection to: "+h6(a)),v8(a,0)):(q6(),HCa(),m8("Skipping connecting because no session screen found."))},$Ca=function(){var a=q8();
if(g.Yb(a)){a=o6();var b=g.QG("yt-remote-session-name")||"",c=g.QG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.wa("yt.mdx.remote.channelParams_",a,void 0)}},q8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},bDa=function(a){a?(g.PG("yt-remote-session-app",a.app),g.PG("yt-remote-session-name",a.name)):(g.RG("yt-remote-session-app"),g.RG("yt-remote-session-name"));
g.wa("yt.mdx.remote.channelParams_",a,void 0)},z8=function(a,b,c){g.L.call(this);
this.F=a;this.l=b;this.o=new g.HF(this);g.M(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.yQ);this.o.O(b,"captionschanged",this.eP);this.o.O(b,"captionssettingschanged",this.qD);this.o.O(b,"videoplayerreset",this.Io);this.o.O(b,"mdxautoplaycancel",this.FH);this.P=this.o.O(b,"onVolumeChange",this.DB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.QB,this);c.subscribe("remotePlayerChange",this.Pl,this);c.subscribe("remoteQueueChange",this.Io,this);c.subscribe("autoplayUpNext",this.mB,
this);c.subscribe("previousNextChange",this.NB,this);c.subscribe("nowAutoplaying",this.FB,this);c.subscribe("autoplayDismissed",this.lB,this);this.suggestion=null;this.H=new g.ZO(64);this.A=new g.Yt(this.mD,500,this);g.M(this,this.A);this.B=new g.Yt(this.nD,1E3,this);g.M(this,this.B);this.K=new y6(this.EU,0,this);g.M(this,this.K);this.C={};this.M=new g.Yt(this.TD,1E3,this);g.M(this,this.M);this.I=new g.Tk(this.iN,1E3,this);g.M(this,this.I);this.N=g.y;this.qD();this.Io();this.Pl()},A8=function(a,b){var c=
a.F,d=a.l.ea().lengthSeconds;
c.H=b||0;c.g.R("progresssync",b,d)},jDa=function(a){A8(a,0);
a.A.stop();B8(a,new g.ZO(64))},D8=function(a,b){if(C8(a)&&!a.D){var c=null;
b&&(c={style:a.l.Ci()},g.ec(c,b));a.g.eD(a.l.ea(1).videoId,c);a.C=V7(a.g).l}},E8=function(a,b){var c=a.l.Vf();
if(c){var d=c.je();var e=c.listId.toString()}var f=a.l.ea(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.Ij;var m=V7(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};R7(m,k,l);g.t(b)&&(P7(m,b),q.currentTime=b);g.t(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);Z7(c,"setPlaylist",q);e||X7(c,m);B8(a,new g.ZO(1))},kDa=function(a,b){if(b){var c=a.l.Ac("captions","tracklist",{Ry:1});
c&&c.length?(a.l.Id("captions","track",b),a.D=!1):(a.l.Qj("captions"),a.D=!0)}else a.l.Id("captions","track",{})},C8=function(a){return V7(a.g).videoId==a.l.ea(1).videoId},B8=function(a,b){a.B.stop();
var c=a.H;if(!g.gP(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.ZU(a.l,d);a.H=b;lDa(a.F,c,b)}},F8=function(a){g.W.call(this,{G:"div",
L:"ytp-remote",J:[{G:"div",L:"ytp-remote-display-status",J:[{G:"div",L:"ytp-remote-display-status-icon",J:[g.yoa()]},{G:"div",L:"ytp-remote-display-status-text",J:["{{statustext}}"]}]}]});this.l=new g.FV(this,250);g.M(this,this.l);this.o=a;this.O(a,"presentingplayerstatechange",this.A);mDa(this,g.WU(a))},mDa=function(a,b){if(3==a.o.Ta()){var c={RECEIVER_NAME:a.o.Ac("remote","currentReceiver").name};
c=g.X(b,128)?g.V("YTP_MDX_STATUS_ERROR_2",c):b.kb()||g.X(b,4)?g.V("YTP_MDX_STATUS_PLAYING_2",c):g.V("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},G8=function(a,b){g.LZ.call(this,g.V("YTP_MDX_TITLE"),0,a,b);
this.l=a;this.F={};this.O(a,"onMdxReceiversChange",this.I);this.O(a,"presentingplayerstatechange",this.I);this.I()},H8=function(a){g.tV.call(this,a);
g.UG({YTP_MDX_CAST_SELECTOR:"Cast...",YTP_MDX_MY_COMPUTER:"This computer",YTP_MDX_PLAYER_ERROR:"This video is not available for remote playback.",YTP_MDX_STATUS_CONNECTED_2:"Connected to $RECEIVER_NAME",YTP_MDX_STATUS_ERROR_2:"Error on $RECEIVER_NAME",YTP_MDX_STATUS_PLAYING_2:"Playing on $RECEIVER_NAME",YTP_MDX_TITLE:"Play on"});this.o={key:j6(),name:g.V("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.ZO(64);this.H=0;if(!g.EM(g.Y(this.g))){a=
this.g;var b=g.kI(a);b&&(b=b.so())&&(b=new G8(a,b),g.M(this,b));b=new F8(a);g.M(this,b);g.nV(a,b.element,4)}},lDa=function(a,b,c){a.D=c;
a.g.R("presentingplayerstatechange",new g.mP(c,b))},I8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)u8();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.ea(1),e=d.videoId;if(c||e){var f=a.g.Vf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.kc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Ij,index:Math.max(a.g.Sz(),0),currentTime:0==f?void 0:f}}else c=null;m8("Connecting to: "+g.zg(b));"cast-selector-receiver"==b.key?(o8(c||null),J7()?G7().setLaunchParams(c||null):E7("setLaunchParams called before ready.")):!c&&
x8()&&l8()==b.key?g.ZF("yt-remote-connection-change",!0):(u8(),o8(c||null),c=k8().ne(),(c=l6(c,b.key))&&v8(c,1))}},BBa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},I6={"'":"\\'"},nDa={},$Aa={sW:"atp",K0:"ska",a0:"que",m_:"mus",G0:"sus"};
e6.prototype.kn=function(){var a=new e6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var r6,n6="",v6=s6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",tBa=s6("loadCastFramework")||s6("loadCastApplicationFramework"),DCa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(y6,g.L);g.h=y6.prototype;g.h.tI=function(a){this.A=arguments;this.g=!1;this.ya?this.o=(0,g.G)()+this.ed:this.ya=g.tg(this.B,this.ed)};
g.h.stop=function(){this.ya&&(g.ug(this.ya),this.ya=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();y6.Y.V.call(this)};
g.h.uI=function(){this.o?(this.ya=g.tg(this.B,this.o-(0,g.G)()),this.o=null):(this.ya=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};z6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
z6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=A6.prototype;g.h.ki=null;g.h.xf=!1;g.h.xk=null;g.h.Wu=null;g.h.dk=null;g.h.xj=null;g.h.hh=null;g.h.Ah=null;g.h.Ji=null;g.h.Sc=null;g.h.im=0;g.h.yf=null;g.h.Cp=null;g.h.ih=null;g.h.dl=-1;g.h.LC=!0;g.h.Uh=!1;g.h.ir=0;g.h.So=null;var zBa={},D6={};g.h=A6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.xT=function(a){a=a.target;var b=this.So;b&&3==g.ix(a)?b.vj():this.bE(a)};
g.h.bE=function(a){try{if(a==this.Sc)a:{var b=g.ix(this.Sc),c=this.Sc.l,d=this.Sc.getStatus();if(g.wd&&!g.rc(10)||g.yd&&!g.qc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.ef&&!g.mx(this.Sc))break a;this.Uh||4!=b||7==c||(8==c||0>=d?this.g.rf(3):this.g.rf(2));K6(this);var e=this.Sc.getStatus();this.dl=e;var f=g.mx(this.Sc);(this.xf=200==e)?(4==b&&G6(this),this.C?(ABa(this,b,f),g.ef&&this.xf&&3==b&&(this.A.T(this.l,"tick",this.uT),this.l.start())):F6(this,f),this.xf&&!this.Uh&&(4==b?this.g.Go(this):
(this.xf=!1,C6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ih=3,E6(13)):(this.ih=0,E6(14)),G6(this),H6(this))}}catch(k){this.Sc&&g.mx(this.Sc)}finally{}};
g.h.uT=function(){var a=g.ix(this.Sc),b=g.mx(this.Sc);this.im<b.length&&(K6(this),ABa(this,a,b),this.xf&&4!=a&&C6(this))};
g.h.FS=function(a){J6((0,g.z)(this.ES,this,a),0)};
g.h.ES=function(a){this.Uh||(K6(this),F6(this,a),C6(this))};
g.h.YB=function(a){J6((0,g.z)(this.DS,this,a),0)};
g.h.DS=function(a){this.Uh||(G6(this),this.xf=a,this.g.Go(this),this.g.rf(4))};
g.h.cancel=function(){this.Uh=!0;G6(this)};
g.h.WS=function(){this.xk=null;var a=(0,g.G)();0<=a-this.Wu?(2!=this.xj&&this.g.rf(3),G6(this),this.ih=2,E6(18),H6(this)):DBa(this,this.Wu-a)};g.h=GBa.prototype;g.h.dr=null;g.h.ue=null;g.h.To=!1;g.h.ey=null;g.h.zn=null;g.h.fr=null;g.h.gr=null;g.h.Me=null;g.h.xg=-1;g.h.bl=null;g.h.Ck=null;g.h.connect=function(a){this.gr=a;a=M6(this.g,null,this.gr);E6(3);this.ey=(0,g.G)();var b=this.g.F;null!=b?(this.bl=b[0],(this.Ck=b[1])?(this.Me=1,HBa(this)):(this.Me=2,O6(this))):(d6(a,"MODE","init"),this.ue=new A6(this,void 0,void 0,void 0),this.ue.ki=this.dr,B6(this.ue,a,!1,null,!0),this.Me=0)};
g.h.GH=function(a){if(a)this.Me=2,O6(this);else{E6(4);var b=this.g;b.If=b.Wg.xg;V6(b,9)}a&&this.rf(2)};
g.h.Dq=function(a){return this.g.Dq(a)};
g.h.abort=function(){this.ue&&(this.ue.cancel(),this.ue=null);this.xg=-1};
g.h.by=function(){return!1};
g.h.RB=function(a,b){this.xg=a.dl;if(0==this.Me)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.If=this.xg;V6(c,2);return}this.bl=c[0];this.Ck=c[1]}else c=this.g,c.If=this.xg,V6(c,2);else if(2==this.Me)if(this.To)E6(7),this.fr=(0,g.G)();else if("11111"==b){if(E6(6),this.To=!0,this.zn=(0,g.G)(),c=this.zn-this.ey,!g.wd||g.rc(10)||500>c)this.xg=200,this.ue.cancel(),E6(12),N6(this.g,this,!0)}else E6(8),this.zn=this.fr=(0,g.G)(),this.To=!1};
g.h.Go=function(){this.xg=this.ue.dl;if(this.ue.xf)0==this.Me?this.Ck?(this.Me=1,HBa(this)):(this.Me=2,O6(this)):2==this.Me&&((!g.wd||g.rc(10)?!this.To:200>this.fr-this.zn)?(E6(11),N6(this.g,this,!1)):(E6(12),N6(this.g,this,!0)));else{0==this.Me?E6(9):2==this.Me&&E6(10);var a=this.g;a.If=this.xg;V6(a,2)}};
g.h.Yl=function(){return this.g.Yl()};
g.h.isActive=function(){return this.g.isActive()};
g.h.rf=function(a){this.g.rf(a)};g.h=P6.prototype;g.h.Nk=null;g.h.Vd=null;g.h.wc=null;g.h.ar=null;g.h.Cn=null;g.h.pw=null;g.h.Qn=null;g.h.Jl=0;g.h.wO=0;g.h.qd=null;g.h.Yg=null;g.h.pg=null;g.h.Yh=null;g.h.Wg=null;g.h.Bp=null;g.h.Mj=-1;g.h.fz=-1;g.h.If=-1;g.h.pj=0;g.h.dj=0;g.h.Wh=8;var W6=new g.Ef;g.A(JBa,g.cf);g.A(KBa,g.cf);g.A(LBa,g.cf);g.h=P6.prototype;g.h.connect=function(a,b,c,d,e){E6(0);this.ar=b;this.Nk=c||{};d&&g.t(e)&&(this.Nk.OSID=d,this.Nk.OAID=e);this.C?(J6((0,g.z)(this.Pw,this,a),100),PBa(this)):this.Pw(a)};
g.h.Pw=function(a){this.Wg=new GBa(this);this.Wg.dr=null;this.Wg.l=this.B;this.Wg.connect(a)};
g.h.by=function(){return 0==this.g};
g.h.WB=function(a){this.Yg=null;SBa(this,a)};
g.h.VB=function(){this.pg=null;this.wc=new A6(this,this.o,"rpc",this.D);this.wc.ki=null;this.wc.ir=0;var a=this.pw.clone();g.Jm(a,"RID","rpc");g.Jm(a,"SID",this.o);g.Jm(a,"CI",this.Bp?"0":"1");g.Jm(a,"AID",this.Mj);Q6(this,a);if(!g.wd||g.rc(10))g.Jm(a,"TYPE","xmlhttp"),B6(this.wc,a,!0,this.Qn,!1);else{g.Jm(a,"TYPE","html");var b=this.wc,c=!!this.Qn;b.xj=3;b.hh=c6(a.clone());CBa(b,c)}};
g.h.RB=function(a,b){if(0!=this.g&&(this.wc==a||this.Vd==a))if(this.If=a.dl,this.Vd==a&&3==this.g)if(7<this.Wh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.pg){if(this.wc)if(this.wc.dk+3E3<this.Vd.dk)S6(this),this.wc.cancel(),this.wc=null;else break a;U6(this);E6(19)}}else this.fz=c[1],0<this.fz-this.Mj&&37500>c[2]&&this.Bp&&0==this.dj&&!this.Yh&&(this.Yh=J6((0,g.z)(this.ZO,this),6E3));else V6(this,11)}else b!=nDa.xX.g&&V6(this,11);else if(this.wc==a&&
S6(this),!g.E(b)){c=this.B.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.Mj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.Qn=e[2],e=e[3],null!=e?this.Wh=e:this.Wh=6,this.g=3,this.qd&&this.qd.Cw(),this.pw=M6(this,this.Yl()?this.Qn:null,this.ar),TBa(this)):"stop"==e[0]&&V6(this,7):3==this.g&&("stop"==e[0]?V6(this,7):"noop"!=e[0]&&this.qd&&this.qd.Bw(e),this.dj=0)}}};
g.h.ZO=function(){null!=this.Yh&&(this.Yh=null,this.wc.cancel(),this.wc=null,U6(this),E6(20))};
g.h.Go=function(a){if(this.wc==a){S6(this);this.wc=null;var b=2}else if(this.Vd==a)this.Vd=null,b=1;else return;this.If=a.dl;if(0!=this.g)if(a.xf)1==b?(b=(0,g.G)()-a.dk,W6.dispatchEvent(new KBa(W6,a.Ji?a.Ji.length:0,b,this.pj)),R6(this),this.A.length=0):TBa(this);else{var c=a.ih,d;if(!(d=3==c||7==c||0==c&&0<this.If)){if(d=1==b)this.Vd||this.Yg||1==this.g||2<=this.pj?d=!1:(this.Yg=J6((0,g.z)(this.WB,this,a),UBa(this,this.pj)),this.pj++,d=!0);d=!(d||2==b&&U6(this))}if(d)switch(c){case 1:V6(this,5);
break;case 4:V6(this,10);break;case 3:V6(this,6);break;case 7:V6(this,12);break;default:V6(this,2)}}};
g.h.bI=function(a){if(!g.D(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.sU=function(a){a?E6(2):(E6(1),VBa(this,8))};
g.h.Dq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.cx;a.F=!1;return a};
g.h.isActive=function(){return!!this.qd&&this.qd.isActive(this)};
g.h.rf=function(a){W6.dispatchEvent(new LBa(W6,a))};
g.h.Yl=function(){return!(!g.wd||g.rc(10))};
g.h=WBa.prototype;g.h.Cw=function(){};
g.h.Bw=function(){};
g.h.Aw=function(){};
g.h.qq=function(){};
g.h.Jx=function(){return{}};
g.h.isActive=function(){return!0};g.A(X6,g.L);g.h=X6.prototype;g.h.wS=function(){this.ed=Math.min(3E5,2*this.ed);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.ed+15E3*Math.random();g.Zt(this.g,a);this.l=(0,g.G)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.ed=5E3};g.A(Y6,WBa);g.h=Y6.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Ld=function(a){return this.o.Ld(a)};
g.h.R=function(a,b){return this.o.R.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.af(this.o),ZBa(this),g.af(this.l),this.l=null)};
g.h.ha=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new P6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.g;e&&(e.qd=null);d.qd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Mj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):Z6(this)&&QBa(this.g,c)};
g.h.Cw=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)QBa(this.g,a[b])}this.R("handlerOpened")};
g.h.Aw=function(a){var b=2==a&&401==this.g.If;4==a||b||this.l.start();this.R("handlerError",a)};
g.h.qq=function(a){if(!this.l.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Jx=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.ec(a,this.B);return a};
g.h.Bw=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),OBa(this.g)):this.R("handlerMessage",new XBa(a[0],a[1]))};
g.h.XU=function(){this.l.isActive();var a=this.g,b=0;a.wc&&b++;a.Vd&&b++;0!=b||this.connect(this.B,this.A)};$6.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
$6.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
$6.prototype.B=function(a){a(Error("request timed out"))};var gCa=(0,g.G)(),c7=null,f7=Array(50),e7=-1,g7=!1;g.A(h7,g.KF);h7.prototype.ne=function(){return this.g};
h7.prototype.contains=function(a){return!!k6(this.g,a)};
h7.prototype.get=function(a){return a?l6(this.g,a):null};
h7.prototype.info=function(a){d7(this.D,a)};g.A(i7,g.KF);var oDa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=i7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.ya)&&this.gE()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.ya)||(g.ZD(this.ya),this.ya=window.NaN)};
g.h.V=function(){this.stop();i7.Y.V.call(this)};
g.h.gE=function(){this.ya=window.NaN;this.g=g.qE(a7(this.C,"/pairing/get_screen"),{method:"POST",Mb:{pairing_code:this.B},timeout:5E3,Ib:(0,g.z)(this.ZU,this),onError:(0,g.z)(this.YU,this),wd:(0,g.z)(this.aV,this)})};
g.h.ZU=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.R("pairingComplete",new f6(c))};
g.h.YU=function(a){this.g=null;a.status&&404==a.status?this.l>=oDa.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=oDa[this.l],this.ya=g.TD((0,g.z)(this.gE,this),a),this.l++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.aV=function(){this.g=null;this.R("pairingFailed",Error("Server not responding"))};g.A(k7,h7);g.h=k7.prototype;g.h.start=function(){j7(this)&&this.R("screenChange");!g.QG("yt-remote-lounge-token-expiration")&&kCa(this);g.ZD(this.l);this.l=g.TD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){j7(this);hCa(this,a);l7(this,!1);this.R("screenChange");b(a);a.token||kCa(this)};
g.h.remove=function(a,b){var c=j7(this);jCa(this,a)&&(l7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.xp=function(a,b,c,d){var e=j7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,l7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.V=function(){g.ZD(this.l);k7.Y.V.call(this)};
g.h.HI=function(a){j7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}l7(this,!b);b&&d7(this.D,"Missed "+b+" lounge tokens.")};
g.h.GI=function(a){d7(this.D,"Requesting lounge tokens failed: "+a)};g.A(n7,g.KF);g.h=n7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.QG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.G)()-144E5<a?0:a)?p7(this):(this.A=(0,g.G)()+3E5,g.PG("yt-remote-fast-check-period",this.A),this.fu())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){m7("Updating availability on schedule.");var a=this.C(),b=g.Mb(this.g,function(b,d){return b&&!!l6(a,d)},this);
o7(this,b)};
g.h.V=function(){g.ZD(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);n7.Y.V.call(this)};
g.h.fu=function(){g.ZD(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=nCa(this);if(g.Pb(a)){var b=a7(this.B,"/pairing/get_screen_availability");this.l=b7(this.B,b,{lounge_token:g.Sb(a).join(",")},(0,g.z)(this.eS,this,a),(0,g.z)(this.dS,this))}else o7(this,{}),p7(this)};
g.h.eS=function(a,b){this.l=null;var c=g.Sb(nCa(this));if(g.jb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;o7(this,d);p7(this)}else this.gc("Changing Screen set during request."),this.fu()};
g.h.dS=function(a){this.gc("Screen availability failed: "+a);this.l=null;p7(this)};
g.h.gc=function(a){d7("OnlineScreenService",a)};g.A(q7,h7);g.h=q7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.R("screenChange"),this.l.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.xp=function(a,b,c,d){this.o.contains(a)?this.o.xp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,d7(this.D,a),d(Error(a)))};
g.h.ne=function(a){return a?this.g:g.Wa(this.g,(0,g.Jd)(this.A,function(a){return!this.contains(a)},this))};
g.h.hE=function(){return(0,g.Jd)(this.ne(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.iE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new i7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.af(f);d(r7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.af(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.cV=function(a,b,c,d){g.qE(a7(this.C,"/pairing/get_screen"),{method:"POST",Mb:{pairing_code:a},timeout:5E3,Ib:(0,g.z)(function(a,d){var e=new f6(d.screen||{});if(!e.name||rCa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);rCa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(r7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
wd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.af(this.o);g.af(this.l);q7.Y.V.call(this)};
g.h.YI=function(){sCa(this);this.R("screenChange");this.l.update()};
q7.prototype.dispose=q7.prototype.dispose;g.A(t7,g.KF);g.h=t7.prototype;g.h.Ho=function(a){this.o=a;this.R("sessionScreen",this.o)};
g.h.se=function(a){this.ha()||(a&&u7(this,""+a),this.o=null,this.R("sessionScreen",null))};
g.h.info=function(a){d7(this.M,a)};
g.h.kE=function(){return null};
g.h.ou=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){u7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.ou("");t7.Y.V.call(this)};g.A(v7,t7);g.h=v7.prototype;g.h.nu=function(a){if(this.g){if(this.g==a)return;u7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);uCa(this)};
g.h.Nj=function(a){this.info("launchWithParams no-op for Cast: "+g.zg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.se()},this),(0,g.z)(function(){this.se(Error("Failed to stop receiver app."))},this)):this.se(Error("Stopping cast device witout session."))};
g.h.ou=g.y;g.h.V=function(){this.info("disposeInternal");g.ZD(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;v7.Y.V.call(this)};
g.h.hT=function(a,b){if(!this.ha())if(b){var c=g.Xw(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.zg(c));switch(d){case "mdxSessionStatus":tCa(this,c.screenId);break;default:u7(this,"Unknown youtube message: "+d)}}else u7(this,"Unable to parse message.")}else u7(this,"No data in message.")};
g.h.Ux=function(a,b,c,d){qCa(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(u7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.TD((0,g.z)(this.Ux,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.kE=function(){return this.g};
g.h.dV=function(a){this.ha()||a||(u7(this,"Cast session died."),this.se())};g.A(w7,t7);g.h=w7.prototype;g.h.nu=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.Nj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.ZD(this.C);this.A?this.A.stop((0,g.z)(this.se,this,null),(0,g.z)(this.se,this,"Failed to stop DIAL device.")):this.se()};
g.h.V=function(){this.g();this.g=g.y;g.ZD(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;w7.Y.V.call(this)};
g.h.gV=function(a){this.ha()||a||(u7(this,"DIAL session died."),this.g(),this.g=g.y,this.se())};
g.h.Rr=function(a){this.I=j6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,wCa(this));a(b);vCa(this)}else this.D=(0,g.z)(function(){g.ZD(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,wCa(this));a(b);vCa(this)},this),this.C=g.TD((0,g.z)(function(){this.D()},this),100)};
g.h.lK=function(a,b,c){qCa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Ho(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Rr(b,c)},this),(0,g.z)(function(a){u7(this,"Failed to get DIAL screen: "+a);
this.Rr(b,c)},this))};g.A(x7,t7);x7.prototype.stop=function(){this.se()};
x7.prototype.nu=g.y;x7.prototype.Nj=function(){g.ZD(this.g);this.g=window.NaN;var a=l6(this.H.ne(),this.l.label);a?this.Ho(a):this.se(Error("No such screen"))};
x7.prototype.V=function(){g.ZD(this.g);this.g=window.NaN;x7.Y.V.call(this)};g.A(y7,g.KF);g.h=y7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.SB,this),(0,g.z)(this.OR,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.KP,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ha()||(window.chrome.cast.addReceiverActionListener(this.A),dCa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.jE,this)),this.o=yCa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.gc("Failed to set initial custom receivers: "+g.zg(a))},this)),this.R("yt-remote-cast2-availability-change",A7(this)),b(!0))},this),(0,g.z)(function(a){this.gc("Failed to initialize API: "+g.zg(a));
b(!1)},this))};
g.h.bU=function(a,b){z7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)z7("Unsetting old screen status: "+this.g.l.friendlyName),B7(this,null)}if(a&&b){if(!this.g){c=l6(this.l.ne(),a);if(!c){z7("setConnectedScreenStatus: Unknown screen.");return}var d=xCa(this,c);d||(z7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.gc("Failed to set initial custom receivers: "+g.zg(a))},this)));
z7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);B7(this,new x7(this.l,d),!0)}this.g.ou(b)}else z7("setConnectedScreenStatus: no screen.")};
g.h.cU=function(a){this.ha()?this.gc("Setting connection data on disposed cast v2"):this.g?this.g.Nj(a):this.gc("Setting connection data without a session")};
g.h.fV=function(){this.ha()?this.gc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),B7(this,null)):z7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.SB,this),(0,g.z)(this.jS,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.jE,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Ua(g.x("yt.mdx.remote.debug.handlers_")||[],aCa);g.af(this.g);y7.Y.V.call(this)};
g.h.gc=function(a){d7("Controller",a)};
g.h.TB=function(a,b){this.g==a&&(b||B7(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.KR=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),z7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)z7("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{z7("onReceiverAction_: Casting to active receiver.");this.g.o&&this.R("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:B7(this,
new x7(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:B7(this,new w7(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:B7(this,new v7(this.l,a));break;default:this.gc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.gc("Stopping receiver w/o session: "+a.friendlyName)}else this.gc("onReceiverAction_ called without receiver.")};
g.h.KP=function(a){if(this.ha())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.gc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.gc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return z7("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.gc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);B7(this,new w7(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.lK,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.Rr,b))};
g.h.SB=function(a){if(!this.ha()){z7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)z7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),B7(this,new v7(this.l,b),!0);else{this.gc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=l6(this.l.ne(),c.label);
d&&g6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(z7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.af(this.g),this.g=new v7(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.TB,this,this.g)),this.g.Nj(null));this.g.nu(a)}}};
g.h.eV=function(){return this.g?this.g.kE():null};
g.h.jS=function(a){this.ha()||(this.gc("Failed to estabilish a session: "+g.zg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&B7(this,null))};
g.h.OR=function(a){z7("Receiver availability updated: "+a);if(!this.ha()){var b=A7(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;A7(this)!=b&&this.R("yt-remote-cast2-availability-change",A7(this))}};
g.h.jE=function(){this.ha()||(this.o=yCa(this),z7("Updating custom receivers: "+g.zg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.gc("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",A7(this)))};
y7.prototype.setLaunchParams=y7.prototype.cU;y7.prototype.setConnectedScreenStatus=y7.prototype.bU;y7.prototype.stopSession=y7.prototype.fV;y7.prototype.getCastSession=y7.prototype.eV;y7.prototype.requestSession=y7.prototype.requestSession;y7.prototype.init=y7.prototype.init;y7.prototype.dispose=y7.prototype.dispose;var H7=[];g.h=M7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";N7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Lf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.kb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+O7(this):this.H};
g.h.clone=function(){return new M7(S7(this))};g.A(U7,g.KF);g.h=U7.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,$7(this,"play")):Z7(this,"play"),Y7(this,1,Q7(V7(this))),this.R("remotePlayerChange")):W7(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,$7(this,"pause")):Z7(this,"pause"),Y7(this,2,Q7(V7(this))),this.R("remotePlayerChange")):W7(this,this.pause)};
g.h.fE=function(a){if(1==this.g){if(this.l){var b=V7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,$7(this,"seekTo",{newTime:a}))}else Z7(this,"seekTo",{newTime:a});Y7(this,3,a);this.R("remotePlayerChange")}else W7(this,g.Fa(this.fE,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,$7(this,"stopVideo")):Z7(this,"stopVideo");var a=V7(this);a.index=-1;a.videoId="";N7(a);X7(this,a);this.R("remotePlayerChange")}else W7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=V7(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){d7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.gc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){d7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.gc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);Z7(this,"setVolume",e)}c.muted=b;c.volume=a;X7(this,c)}else W7(this,g.Fa(this.setVolume,a,b))};
g.h.eD=function(a,b){if(1==this.g){var c=V7(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.zg(b.style),g.ec(d,c.l));Z7(this,"setSubtitlesTrack",d);X7(this,c)}else W7(this,g.Fa(this.eD,a,b))};
g.h.bv=function(a,b){if(1==this.g){Z7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Pb.id});var c=V7(this);c.audioTrackId=b.Pb.id;X7(this,c)}else W7(this,g.Fa(this.bv,a,b))};
g.h.eE=function(a,b){if(1==this.g){if(a&&b){var c=V7(this);R7(c,a,b);X7(this,c)}Z7(this,"previous")}else W7(this,g.Fa(this.eE,a,b))};
g.h.dE=function(a,b){if(1==this.g){if(a&&b){var c=V7(this);R7(c,a,b);X7(this,c)}Z7(this,"next")}else W7(this,g.Fa(this.dE,a,b))};
g.h.kx=function(){1==this.g?Z7(this,"dismissAutoplay"):W7(this,this.kx)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.R("proxyStateChange",a,this.g)}U7.Y.dispose.call(this)};
g.h.V=function(){LCa(this);this.A=null;this.B.clear();T7(this,null);U7.Y.V.call(this)};
g.h.cv=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.mC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.GR=function(a,b){this.R(a,b)};
g.h.gP=function(a){if(!a)this.Ml(null),T7(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=V7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)d7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,X7(this,b)}};
g.h.Ml=function(a){d7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),MCa(this),this.R("remotePlayerChange")};
g.h.fP=function(a){a?(MCa(this),this.R("remotePlayerChange")):this.Ml(null)};
g.h.tP=function(){var a=ICa();a&&T7(this,a)};
g.h.gc=function(a){d7("CP",a)};g.A(a8,g.KF);g.h=a8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Za.listId=c);this.Za.videoId=d;this.Za.index=k||0;this.Za.state=3;P7(this.Za,m);this.A="UNSUPPORTED";b8("Connecting with setPlaylist and params: "+g.zg(l));this.g.connect({method:"setPlaylist",params:g.zg(l)},a,hBa())}else b8("Connecting without params"),
this.g.connect({},a,hBa());OCa(this)};
g.h.dispose=function(){this.ha()||(this.R("beforeDispose"),c8(this,3));a8.Y.dispose.call(this)};
g.h.V=function(){d8(this);f8(this);e8(this);g.ZD(this.H);this.H=window.NaN;g.ZD(this.I);this.I=window.NaN;this.o=null;g.vF(this.P);this.P.length=0;this.g.dispose();a8.Y.V.call(this);this.A=this.D=this.l=this.Za=this.g=null};
g.h.yI=function(){this.C(2)};
g.h.kP=function(){b8("Channel opened");this.N&&(this.N=!1,e8(this),this.M=g.TD((0,g.z)(function(){b8("Timing out waiting for a screen.");this.C(1)},this),15E3));
lBa(YBa(this.g),this.X)};
g.h.hP=function(){b8("Channel closed");(0,window.isNaN)(this.B)?q6(!0):q6();this.dispose()};
g.h.iP=function(a){q6();(0,window.isNaN)(this.F())?(b8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,b8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),c8(this,2))};
g.h.jP=function(a){a.params?b8("Received: action="+a.action+", params="+g.zg(a.params)):b8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Xw(a.params.devices);this.l=(0,g.I)(a,function(a){return new e6(a)});
a=!!g.Ma(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
RCa(this,a);break;case "loungeScreenDisconnected":g.Va(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
RCa(this,!1);break;case "remoteConnected":var b=new e6(g.Xw(a.params.device));g.Ma(this.l,function(a){return b?a.id==b.id:!1})||g.Sa(this.l,b);
break;case "remoteDisconnected":b=new e6(g.Xw(a.params.device));g.Va(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":TCa(this,a);break;case "nowPlaying":VCa(this,a);break;case "onStateChange":UCa(this,a);break;case "onAdStateChange":WCa(this,a);break;case "onVolumeChanged":XCa(this,a);break;case "onSubtitlesTrackChanged":SCa(this,a);break;case "nowAutoplaying":YCa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.R("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.R("autoplayModeChange",this.A);"DISABLED"==this.A&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":ZCa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:b8("Unrecognized action: "+a.action)}};
g.h.JT=function(){if(this.o){var a=this.o;this.o=null;this.Za.videoId!=a&&g8(this,"getNowPlaying")}};
a8.prototype.subscribe=a8.prototype.subscribe;a8.prototype.unsubscribeByKey=a8.prototype.Ld;a8.prototype.fa=function(){var a=3;this.ha()||(a=0,(0,window.isNaN)(this.F())?Z6(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
a8.prototype.getProxyState=a8.prototype.fa;a8.prototype.C=function(a){b8("Disconnecting with "+a);d8(this);this.R("beforeDisconnect",a);1==a&&q6();ZBa(this.g,a);this.dispose()};
a8.prototype.disconnect=a8.prototype.C;a8.prototype.da=function(){var a=this.Za;this.o&&(a=this.Za.clone(),R7(a,this.o,a.index));return S7(a)};
a8.prototype.getPlayerContextData=a8.prototype.da;
a8.prototype.ma=function(a){var b=new M7(a);b.videoId&&b.videoId!=this.Za.videoId&&(this.o=b.videoId,g.ZD(this.H),this.H=g.TD((0,g.z)(this.JT,this),5E3));var c=[];this.Za.listId==b.listId&&this.Za.videoId==b.videoId&&this.Za.index==b.index||c.push("remoteQueueChange");this.Za.g==b.g&&this.Za.volume==b.volume&&this.Za.muted==b.muted&&Q7(this.Za)==Q7(b)&&g.zg(this.Za.l)==g.zg(b.l)||c.push("remotePlayerChange");this.Za.reset(a);(0,g.B)(c,function(a){this.R(a)},this)};
a8.prototype.setPlayerContextData=a8.prototype.ma;a8.prototype.W=function(){var a=this.g.C.id,b=g.Ma(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
a8.prototype.getOtherConnectedRemoteId=a8.prototype.W;a8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.G)():window.NaN};
a8.prototype.getReconnectTimeout=a8.prototype.F;a8.prototype.ba=function(){return this.A||"UNSUPPORTED"};
a8.prototype.getAutoplayMode=a8.prototype.ba;a8.prototype.ca=function(){return this.D||""};
a8.prototype.getAutoplayVideoId=a8.prototype.ca;a8.prototype.ra=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.$t(a.g);a.start()}};
a8.prototype.reconnect=a8.prototype.ra;a8.prototype.ka=function(a,b){g8(this,a,b);QCa(this)};
a8.prototype.sendMessage=a8.prototype.ka;g.A(h8,h7);g.h=h8.prototype;g.h.ne=function(a){return this.dd.$_gs(a)};
g.h.contains=function(a){return!!this.dd.$_c(a)};
g.h.get=function(a){return this.dd.$_g(a)};
g.h.start=function(){this.dd.$_st()};
g.h.add=function(a,b,c){this.dd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.dd.$_r(a,b,c)};
g.h.xp=function(a,b,c,d){this.dd.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.dd.$_ubk(this.l[a]);this.l.length=0;this.dd=null;h8.Y.V.call(this)};
g.h.bV=function(){this.R("screenChange")};
g.h.gR=function(){this.R("onlineScreenChange")};
q7.prototype.$_st=q7.prototype.start;q7.prototype.$_gspc=q7.prototype.cV;q7.prototype.$_gsppc=q7.prototype.iE;q7.prototype.$_c=q7.prototype.contains;q7.prototype.$_g=q7.prototype.get;q7.prototype.$_a=q7.prototype.add;q7.prototype.$_un=q7.prototype.xp;q7.prototype.$_r=q7.prototype.remove;q7.prototype.$_gs=q7.prototype.ne;q7.prototype.$_gos=q7.prototype.hE;q7.prototype.$_s=q7.prototype.subscribe;q7.prototype.$_ubk=q7.prototype.Ld;var i8=null,j8=null,y8=null,n8=[];g.p(z8,g.L);g.h=z8.prototype;
g.h.V=function(){g.L.prototype.V.call(this);this.A.stop();this.B.stop();this.K.stop();this.N();this.g.unsubscribe("proxyStateChange",this.QB,this);this.g.unsubscribe("remotePlayerChange",this.Pl,this);this.g.unsubscribe("remoteQueueChange",this.Io,this);this.g.unsubscribe("autoplayUpNext",this.mB,this);this.g.unsubscribe("previousNextChange",this.NB,this);this.g.unsubscribe("nowAutoplaying",this.FB,this);this.g.unsubscribe("autoplayDismissed",this.lB,this);this.g=this.F=null};
g.h.oA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(C8(this)){if(!V7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":V7(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.vj(c[0],c[1]);break;case "control_subtitles_set_track":D8(this,c[0]);break;case "control_set_audio_track":c=c[0],C8(this)&&this.g.bv(this.l.ea(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();E8(this,0==c?void 0:c);break;case "control_seek":E8(this,c[0]);break;case "control_subtitles_set_track":D8(this,c[0]);break;case "control_set_audio_track":c=c[0],C8(this)&&this.g.bv(this.l.ea(1).videoId,c)}};
g.h.eP=function(a){this.K.tI(a)};
g.h.EU=function(a){this.oA("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.qD=function(){var a=this.l.Ac("captions","track");g.Yb(a)||D8(this,a)};
g.h.DB=function(a){if(C8(this)){this.g.unsubscribe("remotePlayerChange",this.Pl,this);var b=Math.round(a.volume);a=!!a.muted;var c=V7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.M.start();this.g.subscribe("remotePlayerChange",this.Pl,this)}};
g.h.yQ=function(){g.Yb(this.C)||kDa(this,this.C);this.D=!1};
g.h.QB=function(a,b){this.B.stop();2==b&&this.nD()};
g.h.Pl=function(){if(C8(this)){this.A.stop();var a=V7(this.g);switch(a.g){case 1081:case 1:B8(this,new g.ZO(8));this.mD();break;case 1085:case 3:B8(this,new g.ZO(9));break;case 1083:case 0:B8(this,new g.ZO(2));this.I.stop();A8(this,this.l.ea().lengthSeconds);break;case 1084:B8(this,new g.ZO(4));break;case 2:B8(this,new g.ZO(4));A8(this,Q7(a));break;case -1:B8(this,new g.ZO(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.V("YTP_MDX_PLAYER_ERROR")},B8(this,new g.ZO(128,a))}a=V7(this.g).l;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,kDa(this,a));a=V7(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.M.isActive()||this.TD()}else jDa(this)};
g.h.NB=function(){this.l.R("mdxpreviousnextchange")};
g.h.Io=function(){C8(this)||jDa(this)};
g.h.FH=function(){this.g.kx()};
g.h.mB=function(a){a&&(a=g.qE("/watch_queue_ajax",{method:"GET",Zc:{action_get_watch_queue_item:1,video_id:a},Ib:(0,g.z)(this.IS,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.IS=function(a,b){var c=new g.ZN({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.R("mdxautoplayupnext",c)};
g.h.FB=function(a){(0,window.isNaN)(a)||this.l.R("mdxnowautoplaying",a)};
g.h.lB=function(){this.l.R("mdxautoplaycanceled")};
g.h.iN=function(a,b){-1==V7(this.g).g?E8(this,a):b&&this.g.fE(a)};
g.h.TD=function(){if(C8(this)){var a=V7(this.g);this.o.Ba(this.P);a.muted?this.l.mute():this.l.Wf();this.l.setVolume(a.volume);this.P=this.o.O(this.l,"onVolumeChange",this.DB)}};
g.h.mD=function(){this.A.stop();if(!this.g.ha()){var a=V7(this.g);a.kb()&&B8(this,new g.ZO(8));A8(this,Q7(a));this.A.start()}};
g.h.nD=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(F8,g.W);F8.prototype.A=function(a){mDa(this,a.state)};g.p(G8,g.LZ);G8.prototype.I=function(){var a=this.l.Ac("remote","receivers");a&&1<a.length&&!this.l.Ac("remote","quickCast")?(this.F=g.lb(a,this.B,this),g.MZ(this,(0,g.I)(a,this.B)),a=this.l.Ac("remote","currentReceiver"),this.qf(this.B(a)),this.enable(!0)):this.enable(!1)};
G8.prototype.B=function(a){return a.key};
G8.prototype.pf=function(a){return"cast-selector-receiver"==a?g.V("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
G8.prototype.td=function(a){g.LZ.prototype.td.call(this,a);this.l.Id("remote","currentReceiver",this.F[a]);this.A.Qb()};g.p(H8,g.tV);g.h=H8.prototype;g.h.create=function(){dDa(g.sM(g.Y(this.g)));this.C.push(g.VF("yt-remote-before-disconnect",this.aP,this));this.C.push(g.VF("yt-remote-connection-change",this.PR,this));this.C.push(g.VF("yt-remote-receiver-availability-change",this.OB,this));this.C.push(g.VF("yt-remote-auto-connect",this.NR,this));this.C.push(g.VF("yt-remote-receiver-resumed",this.MR,this));this.OB()};
g.h.load=function(){this.g.Ss();g.tV.prototype.load.call(this);this.B=new z8(this,this.g,this.l);var a=(a=iDa())?a.currentTime:0;var b=x8()?new U7(s8(),void 0):null;0==a&&b&&(a=Q7(V7(b)));0!=a&&(this.H=a||0,this.g.R("progresssync",a,void 0));lDa(this,this.D,this.D);g.W_(this.g.app,6)};
g.h.unload=function(){this.g.R("mdxautoplaycanceled");this.A=this.o;g.bf(this.B,this.l);this.l=this.B=null;g.tV.prototype.unload.call(this);g.W_(this.g.app,5)};
g.h.V=function(){g.WF(this.C);g.tV.prototype.V.call(this)};
g.h.El=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.oA.apply(this.B,[].concat([a],g.qa(c)))};
g.h.pI=function(){return this.loaded?this.B.suggestion:null};
g.h.Lf=function(){return this.l?V7(this.l).Lf:!1};
g.h.hasNext=function(){return this.l?V7(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.WM=function(){var a=V7(this.l),b=this.g.ea();return{allowSeeking:this.g.gd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+O7(a):a.A,isPeggedToLive:1>=(a.C?a.o+O7(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+O7(a):a.o,seekableStart:0<a.B?a.B+O7(a):a.B}};
g.h.XM=function(){this.l&&this.l.dE()};
g.h.YM=function(){this.l&&this.l.eE()};
g.h.aP=function(a){1==a&&(this.I=this.l?V7(this.l):null)};
g.h.PR=function(){var a=x8()?new U7(s8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.af(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.ea().videoId&&this.g.Qz(a.videoId,Q7(a)));this.g.R("videodatachange","newdata",this.g.ea(),3)};
g.h.OB=function(){this.F=[this.o].concat(fDa());var a=t8()||this.o;I8(this,a);this.g.sa("onMdxReceiversChange")};
g.h.NR=function(){var a=t8();I8(this,a)};
g.h.MR=function(){this.A=t8()};
g.h.VM=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?K7():I8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&K7(),!0):!1}};
g.h.ZM=function(){Z7(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Rc=function(){return!1};g.fY.remote=H8;})(_yt_player);
